export default Object.freeze({
    PENDING: 'PENDING',
    ACTIVE: 'ACTIVE',
    DELETED: 'DELETED',
    BLOCKED: 'BLOCKED',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    FAILED: 'FAILED',
    SUBMITTED: 'SUBMITTED',
    ACCEPTED: 'ACCEPTED',
    OPEN: 'OPEN',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    EXPIRED: 'EXPIRED'
})
